stages:
    - check:build
    - deploy:build

# ---

check:build:image:postgresql:
    before_script:
        - 'export DOCKER_HOST=tcp://docker:2375'
    except:
        - generated
        - master
    image:
        entrypoint: ['']
        name: docker:stable
    retry:
        max: 2
    script:
        - 'docker build --pull --tag "${CI_REGISTRY_IMAGE}":"${CI_COMMIT_REF_SLUG}" src'
    services:
        - docker:stable-dind
    stage: check:build

deploy:build:image:postgresql:
    before_script:
        - 'export DOCKER_HOST=tcp://docker:2375'
        - 'docker login --password "${CI_REGISTRY_PASSWORD}" --username "${CI_REGISTRY_USER}" registry.gitlab.com'
        - 'docker login --password "${HUB_REGISTRY_PASSWORD}" --username "${HUB_REGISTRY_USER}"'
    image:
        entrypoint: ['']
        name: docker:stable
    only:
        - master
    retry:
        max: 2
    script:
        - 'docker build --pull --tag "${CI_REGISTRY_IMAGE}":latest src'
        - 'docker push "${CI_REGISTRY_IMAGE}":latest'
        - 'docker tag "${CI_REGISTRY_IMAGE}":latest "${HUB_REGISTRY_IMAGE}":latest'
        - 'docker push "${HUB_REGISTRY_IMAGE}":latest'
    services:
        - docker:stable-dind
    stage: deploy:build

deploy:build:rootfs:
    before_script:
        - 'apk add --no-cache --no-progress ca-certificates git'
        - 'git config --global user.email "${GIT_USER_EMAIL}"'
        - 'git config --global user.name "${GIT_USER_NAME}"'
        - 'git remote set-url origin "https://${GITLAB_USER}:${GITLAB_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git"'
    image:
        entrypoint: ['']
        name: alpine:latest
    only:
        - master
    retry:
        max: 2
    script:
        - '( cd src/rootfs && tar --create --file ../../generated/rootfs.tar.gz --gzip --verbose ./ )'
        - 'rm -f -r $(ls | grep -v generated)'
        - 'mv generated/* ./'
        - 'rm -f -r .gitignore .gitlab-ci.yaml .php_cs.dist generated'
        - 'git checkout --orphan generated'
        - 'git add -A'
        - 'git commit -m "$(date --utc ''+%Y-%m-%d %H:%M'')"'
        - 'git push origin generated --force'
    stage: deploy:build
